### ISSUE TITLE
Follow-ups from #128: the composer restore path bypasses the attachment cap, overwrites drafts, and has no tests

### ISSUE THREAD

**Issue by agc129** [rahulkohli31/bial-cd-active#154]
Four items left open when #128 merged (`74029e7`). None blocked the merge; all four live in the
composer's upload-failure restore path, and items 1 and 3 are related — 3 is why 1 shipped.

Found in the round-3 review, each reproduced by probe against the real page or hook in an isolated
worktree. Line numbers are as of `74029e7`.

---

### 1. `restorePending`'s merge applies no cap, so a failed upload can stage — and send — 10 attachments against a limit of 5

`portal/src/hooks/usePendingAttachments.ts:156`

Round 2 asked for `restorePending` to merge-with-dedupe rather than replace, **and never said to
re-apply the per-message cap** — that omission is on the review, not on the implementation. The
merge appends the whole restored batch unconditionally:

```js
const seen = new Set(pendingRef.current.map((a) => a.id))
pendingRef.current = [...pendingRef.current, ...items.filter((a) => !seen.has(a.id))]
```

`handleFiles` re-checks `MAX_FILES_PER_MESSAGE` against `pendingRef.current` at commit time for
exactly this reason; `restorePending` does not.

**Reproduced:** stage 5 files, Send. `doSend` clears the composer and `fireMessage` awaits
`buildUserParts`; the composer stays live with no spinner (the comment at `ChatPage.tsx:409` says
so deliberately), so the user stages 5 more — these validate against an empty list and are
accepted. The upload then fails (per-user storage cap, which the comment at `ChatPage.tsx:404`
calls "routine"). The restore merges the first 5 back: **10 chips, no cap toast.** Pressing Send
sends them all — `validateConversationAttachmentCap` only checks the 20-per-conversation count,
and `validateAttachmentFiles` (the sole enforcement point for the 5-file cap) is never called
again. `buildUserParts` was measured being invoked with 10 attachments.

It compounds across repeated failed sends (5 → 10 → 15 → 20), and at the storage cap every upload
fails, so that is the steady state rather than a one-off. Two side effects: attaching one more
file then fires *"You can attach at most 5 files per message"* while 7 are visibly staged, and the
same path doubles `MAX_TEXT_BYTES_PER_CONVERSATION` for csv/txt — whose inline text is replayed on
every subsequent turn, which is what the 512 kB bound exists to prevent on a metered product.

**Fix** — same clamp `handleFiles` already uses, and toast when it bites:

```js
const seen = new Set(pendingRef.current.map((a) => a.id))
const fresh = items.filter((a) => !seen.has(a.id))
const room = Math.max(0, MAX_FILES_PER_MESSAGE - pendingRef.current.length)
if (fresh.length > room) showAttachToast(`You can attach at most ${MAX_FILES_PER_MESSAGE} files per message.`)
pendingRef.current = [...pendingRef.current, ...fresh.slice(0, room)]
setPendingAttachments(pendingRef.current)
```

Truncate the *restored* batch rather than the newly-staged one — the user can see and re-pick what
they just staged, but has no idea what was dropped from the restore.

---

### 2. The restore replaces the composer text, destroying anything typed during the upload window

`portal/src/pages/ChatPage.tsx:415`

Attachments now merge-with-dedupe; the draft is still a blind replace. The rationale written for
the attachment half applies verbatim to the text half — *"the composer stays live while the send
that's being restored-from was failing, so the user may already have staged something new — a
plain replace would discard it"* (`usePendingAttachments.ts:157-159`) — and was applied to only
one of the two.

No chat switch needed. **Reproduced:** stage `report.png`, type `MESSAGE ONE`, Enter. `doSend`
clears the composer; `generating` is still false so the textarea is live with no spinner. User
starts the next thought — `MESSAGE TWO`. Upload fails, the chat-id guard passes (same chat), and
the composer is overwritten with `MESSAGE ONE`.

`MESSAGE TWO` is unrecoverable — **ctrl+Z will not bring it back**. `@assistant-ui/react`'s
`ComposerPrimitive.Input` renders a fully controlled textarea (`const value = useComposerInputValue()`),
so a store write bypasses the browser's native undo stack.

Same mechanism on a same-chat double send: `if (generating) return` at `ChatPage.tsx:380` does not
block a second send during the upload window (probed — `buildUserParts` called twice with
`["SEND ONE","SEND TWO"]`), so SEND ONE's failure sets the composer to `SEND ONE` while SEND TWO
is still in flight.

**Fix** — restore only into an empty composer, or prepend:

```js
const cur = runtime.thread.composer.text
runtime.thread.composer.setText(cur ? `${rawText}\n\n${cur}` : rawText)
```

---

### 3. The whole upload-failure branch has no test — five mutants survive the full 1325-test suite

`portal/src/pages/ChatPage.tsx:414`

No test in `portal/` mocks `buildUserParts` for ChatPage, so the toast, the chat-scope guard, the
`setText` restore and the `restorePending` call are all unexercised. `usePendingAttachments.test.ts`
pins `restorePending` at the hook level but never touches the ChatPage call site.

| Mutation | Result |
|---|---|
| delete `if (activeChatIdRef.current !== currentChatId) return` | survived — 1325/1325, `tsc` clean |
| invert it to `=== currentChatId` | survived |
| move the guard above `showAttachToast(...)` | survived |
| delete `restorePending(attachments)` | survived, `tsc` clean |
| delete `runtime.thread.composer.setText(rawText)` | survived |

The guard is the entire fix for the cross-chat leak that held this PR for two rounds, and it is
one careless edit from returning with every gate green. Deleting it also leaves eslint quiet,
because `restorePending` stays in the `useCallback` dep array.

**Fix** — two tests in `ChatPage-sendpath.test.jsx`, both written and verified during review:

- Mock `../../utils/attachmentStore`'s `buildUserParts` with a deferred rejection, send from
  chat-1, click through to chat-2 in the sidebar, type a distinct draft there, reject the upload,
  assert the composer still reads chat-2's draft. Passes at HEAD; under the guard mutant fails
  with `expected 'CHAT ONE SECRET DRAFT' to be 'chat two draft'`. Kills mutants 1, 2 and 5.
- Same-chat sibling asserting `text="my draft"` and the chip is back. Kills mutants 3 and 4.

---

### 4. `clearPending()`'s generation bump also fires on every send, silently dropping an in-flight file read

`portal/src/hooks/usePendingAttachments.ts:151`

`generationRef` is documented as guarding chat switches, but `clearPending()` is also `doSend`'s
optimistic clear (`ChatPage.tsx:506`) and BuilderPage's `onSent` clear (`BuilderPage.tsx:1508`).
Any `handleFiles` read still awaiting `fileToBase64` when a send happens is dropped at line 104
with no chip, no toast and no log.

**Reproduced:** drop a large PDF and hit Enter before the read resolves — the attachment vanishes
with zero feedback. The user believes it was attached and the model never sees it. Before #128 the
read appended and the file stayed staged for the next message.

**Fix** — separate the two concerns: keep the generation bump for chat switches, and on the send
path either let in-flight reads land in the now-empty composer or surface a toast when one is
discarded. The `generationRef` docblock ("fired on every chat switch") needs updating either way,
since that is currently only half the story.

---

### Notes

- Items 1 and 4 are behaviour changes introduced by #128; item 2 is a new way to lose typed
  content that did not exist before (`main` restored nothing, so newly typed text survived).
- Item 3 is what let items 1 and 2 ship undetected, and is the third consecutive review round in
  which the fix for the previous round's finding arrived unpinned. Worth doing first.
- **Explicitly not in scope:** the cumulative text-byte budget being exceeded by two *concurrent
  drops*. That reproduces identically on `main` — `attachmentInput.ts` is untouched by #128 — so
  it is pre-existing and belongs in its own issue. The file-count cap got a commit-time re-check
  and the byte budget never did.

**Comment by Anoushka55** [comment]
All four fixed in #155 — not closing this, the merge will.

| # | Fix |
|---|---|
| 1 | `restorePending` clamps to `MAX_FILES_PER_MESSAGE`, truncating the **restored** batch rather than what the user just staged, and toasts when it bites |
| 2 | The draft restore prepends (`rawText\n\n` + what's there) instead of overwriting |
| 3 | New `ChatPage-restore.test.jsx` covering the whole upload-failure branch, plus 5 `usePendingAttachments` cases |
| 4 | `clearPending` split into `clearPending` (chat switch, still bumps the generation) and `clearPendingAfterSend` (send, lets an in-flight read land and stage for the next message); both pages rewired and the `generationRef` docblock corrected |

**Mutation matrix — 8/8 killed:** your five, plus reverting the prepend to a blind `setText`, removing the cap clamp or its toast, and making `clearPendingAfterSend` bump the generation.

Two deviations from the suggested fixes, both deliberate:

- **`runtime.thread.composer.text` doesn't exist** on `ThreadComposerRuntime` in `@assistant-ui/react@0.15.14` — checked against the installed `.d.ts`, the accessor is `.getState().text`. Used that.
- **Tests went in a new file, not `ChatPage-sendpath.test.jsx`.** Mocking `attachmentStore` there changes the module graph for all 74 tests in it; the repo already splits ChatPage tests per concern. `ChatPage-restore.test.jsx` mocks only `buildUserParts` via `importOriginal`, so the rest of the attachment pipeline stays real.

One thing that isn't yours and isn't mine: `UsersLimitsPanel > does not append a stale-cursor page` and `GlobalLimitsPanel > isCapped` fail under full-suite CPU contention and pass in isolation. The first **reproduces on `main` with none of #155 applied**, and neither has an import path to anything the PR touches — so they're pre-existing timer flakes, not regressions. Left alone rather than papered over; happy to file them separately if you'd like them tracked.

**Comment by agc129** [comment]
Closed as fixed on feat/sandbox-first-workspace: the new Composer clears nothing until the server confirms the send (so there is no restore path to race), the file cap is enforced at intake in runtime/attachmentAdapter.ts, and the cross-chat and draft-overwrite cases are pinned in portal/src/components/chat/__tests__/Composer.failurepath.test.tsx. This branch merges to main together with the fix, so no separate hotfix is needed. One caveat for the record: the in-flight-file-read case has no real test (the test meant for it stages no file), so that one is fixed by construction only.

**Comment by agc129** [comment]
Reopening — this was closed in error. These three issues are meant to be closed by the pull request that fixes them when it merges to main, not ahead of that. Sorry for the noise; leaving this open.

**Comment by agc129** [comment]
**#214 rewrites this code path. Item 1 must be resolved there or explicitly carried forward — it cannot be left to drift.**

Two of the four items are affected directly:

**Item 1 (the cap bypass) — same code, must not collide.** #214 changes when an upload happens: files are stored and placed in the workspace at *attach* time rather than at send, and it adds a requirement (R21a) that a file is visibly pending until both have completed, with Send unavailable while anything is pending. That changes the shape of the restore path this item describes, and adds failure modes for it to restore from. Fixing the cap clamp separately, then rewriting the same function in #214, is the worst of both.

**Item 1's second half (the doubled text budget) — disappears entirely.** #214 removes the inline-text lane: `.txt` is dropped, CSV becomes an uploaded file, and `MAX_TEXT_BYTES_PER_CONVERSATION` and `textAttachmentBytes` are deleted. The `MAX_FILES_PER_MESSAGE` half of the bypass remains real and still needs the clamp.

Items 2–4 (draft overwrite, tests) are independent of #214 and stand on their own merits.

Recommendation: fold item 1 into #214 rather than fixing it first, and keep this issue open for the rest. If #214 lands without it, the clamp is still missing and the restore path is now newer than this issue's line references.

**Comment by agc129** [comment]
## Status against the merged attachment work — mostly resolved, but not on `main`, so staying open

PR #224 squash-merged as `fc1e84b6` — onto **`feat/attachments-integration`, not `main`**. The
integration branch is `origin/main` + `ac04e7f9` (#237) + `fc1e84b6` (#224), and nothing is currently
open to merge it to `main`.

That distinction is the whole reason this comment is not a closure. The closing condition on this
issue is already written here: *"These three issues are meant to be closed by the pull request that
fixes them when it merges to main, not ahead of that."* And the precedent is on this very issue —
**#155 claimed all four items fixed, was reviewed, and is closed having never merged**; the last time
this issue was closed on branch-only evidence it had to be reopened as "closed in error."

So: item by item, what is true on `main` today versus what arrives when the integration branch lands.

| item | on `main` today | after `feat/attachments-integration` lands |
|---|---|---|
| **1** file-cap half | **fixed** — the adapter's `claimed` map and `countable()` are on main (`attachmentAdapter.ts:105-125`), so the concurrent-gesture cap does hold at five | unchanged |
| **1** server-side half | **still open** — see below | fixed |
| **1** doubled text budget | **still live** — see below | moot |
| **2** draft overwritten by the restore | **fixed** — `ComposerBox.tsx:172/177/187` carry the conversation stamp, the "CLEARED ONLY ON SUCCESS" comment and the `kept` prefix-slice | unchanged |
| **3** no test on the upload-failure branch | **fixed** — `Composer.failurepath.test.tsx` present at 147 lines with all four describes | unchanged |
| **4** in-flight read dropped on send | **still live** — see below | fixed |

### Item 1's server-side half is still open on `main`

The load-bearing claim that the client adapter is "no longer the sole enforcement point" is **not true
on main**: `backend/src/api/v1/conversations/_shared.py` has no combined bound at all, and
`MAX_ATTACHMENT_BLOCKS = 8` applies *per list*, so the server accepts 8 `attachment_texts` + 8
`attachment_ids` = **16 on one message** and never mentions the 5-file cap. The combined
`MAX_FILES_PER_MESSAGE` check is a #214 R7b change that exists only on the branch. Until it lands, the
client adapter remains the single point of enforcement — precisely the fragility item 1 named.

### Item 1's doubled-text-budget half is not yet moot

It becomes moot when the inline-text lane goes, and that deletion is on the branch, not on main:
`attachmentInput.ts:21` on main is still
`TEXT_MEDIA_TYPES = new Set(['text/csv', 'text/plain'])`, so the inline lane and the 512 kB
per-conversation budget are both live.

### Item 4 is still reproducible on `main`, with its original harm intact

Main has the adapter's private `reading` counter for claim bookkeeping, but **no `onReadingChanged`,
no `usePendingAttachmentReads`, no "Adding your file…" line, and no `if (attachmentsArriving) return`
in `doSend`** — `grep -c usePendingAttachmentReads` on main's `ComposerBox.tsx` returns 0. So on main a
citizen drops a 4 MB workbook, presses Enter before the read resolves, and the question is sent without
the file: no chip, no toast, no log. That is the reproduction in item 4's body.

On the branch the mechanism changes — the file now stages for the *next* message rather than being
generation-bumped away — but this item's asked-for remedy, surfacing something when a read is
discarded, has no equivalent on main. Item 4's first real test,
`Composer.pendingreads.test.tsx` (drops a real CSV, holds `fileToBase64` open, proves the press is
refused), is also branch-only; main's `Composer.failurepath.test.tsx:79-103` stages no file at all —
it types text, presses Enter and fails the send — which matches the caveat already recorded on this
issue that "the test meant for it stages no file, so that one is fixed by construction only."

### One thing that is *not* a reason to keep this open

A file dropped after the press, whose read is still outstanding when `clearAttachments()` runs, is
benign: the library appends the resolved attachment after the clear, so it stages for the next message
rather than vanishing.

### Recommendation

Leave open, and close it the moment `feat/attachments-integration` merges to `main` — at which point
items 1 and 4 become true as written and all four are genuinely resolved. Worth noting for that merge:
GitHub will not close this automatically, and #224's own `Closes #214` silently failed because it was
written inside backticks, which GitHub parses as a code span (`closingIssuesReferences` on #224 was
empty). Close by hand, or put a bare `Closes #154` in the integration-to-main PR body.

Refs #224, #214, #155.
